# Generated by Django 4.0 on 2021-12-28 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('rej_log', '0003_user_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/'),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
