# Generated by Django 4.0 on 2021-12-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rej_log', '0008_alter_relationship_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='profile_img',
            field=models.ImageField(blank=True, default='avatar.jpg', null=True, upload_to='profile_pic'),
        ),
    ]
