# Generated by Django 4.0 on 2021-12-29 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rej_log', '0009_alter_user_details_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='profile_img',
            field=models.ImageField(blank=True, default='profile_pic/avatar.jpg', null=True, upload_to='profile_pic'),
        ),
    ]
