# Generated by Django 4.0 on 2021-12-30 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rej_log', '0006_alter_relationship_status'),
        ('rej_log', '0008_alter_relationship_status'),
        ('rej_log', '0014_alter_user_details_profile_img'),
    ]

    operations = [
    ]
