# Generated by Django 3.2.9 on 2021-12-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rej_log', '0015_merge_20211230_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='status',
            field=models.CharField(choices=[('send', 'send'), ('accepted', 'accepted')], max_length=8),
        ),
    ]
