# Generated by Django 3.2.9 on 2021-12-31 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rej_log', '0015_merge_20211230_1539'),
        ('rej_log', '0017_alter_relationship_status'),
    ]

    operations = [
    ]
