# Generated by Django 3.2.9 on 2021-12-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rej_log', '0008_alter_relationship_status'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, related_name='likes', to='rej_log.User_details'),
        ),
    ]
